# Generated by Django 2.1.7 on 2019-04-18 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garage_exception_table',
            fields=[
                ('path_num', models.AutoField(primary_key=True, serialize=False)),
                ('exception_type', models.CharField(max_length=20)),
                ('exception_description', models.CharField(max_length=200)),
                ('report_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'garage_exception_table',
            },
        ),
        migrations.CreateModel(
            name='Garage_info_table',
            fields=[
                ('garage_num', models.AutoField(primary_key=True, serialize=False)),
                ('investor_num', models.CharField(max_length=20)),
                ('garage_code', models.CharField(max_length=14)),
                ('pub_code', models.CharField(max_length=14)),
                ('garage_name', models.CharField(max_length=15)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('address', models.CharField(max_length=30)),
                ('operation_state', models.CharField(max_length=3)),
                ('running_state', models.CharField(max_length=20)),
                ('door_state', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'garage_info_table',
            },
        ),
        migrations.CreateModel(
            name='Garage_parking_state_table',
            fields=[
                ('state_num', models.AutoField(primary_key=True, serialize=False)),
                ('parking_num', models.IntegerField()),
                ('exist_car', models.BooleanField()),
                ('parking_start_time', models.DateTimeField(blank=True)),
                ('charge_wattage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('charge_state', models.IntegerField()),
                ('lock_state', models.BooleanField()),
                ('charge_key', models.CharField(max_length=32)),
                ('control_state', models.NullBooleanField()),
                ('garage_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsapp.Garage_info_table')),
            ],
            options={
                'db_table': 'garage_parking_state_table',
            },
        ),
        migrations.CreateModel(
            name='Parking_financial_table',
            fields=[
                ('financial_num', models.AutoField(primary_key=True, serialize=False)),
                ('parking_num', models.IntegerField()),
                ('parking_start_time', models.DateTimeField()),
                ('charge_wattage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('charge_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('parking_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('parking_end_time', models.DateTimeField()),
                ('red_packet_expense', models.DecimalField(decimal_places=0, max_digits=3)),
                ('garage_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsapp.Garage_info_table')),
            ],
            options={
                'db_table': 'parking_financial_table',
            },
        ),
        migrations.CreateModel(
            name='Recharge_record_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recharge_num', models.DecimalField(decimal_places=0, max_digits=3)),
                ('red_packet', models.DecimalField(decimal_places=0, max_digits=3)),
                ('recharge_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recharge_record_table',
            },
        ),
        migrations.CreateModel(
            name='Upload_file_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50)),
                ('path_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsapp.Garage_exception_table')),
            ],
            options={
                'db_table': 'upload_file_table',
            },
        ),
        migrations.CreateModel(
            name='User_info_table',
            fields=[
                ('user_num', models.AutoField(primary_key=True, serialize=False)),
                ('phone_num', models.CharField(max_length=11)),
                ('prepaid_wallet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('red_packet', models.DecimalField(decimal_places=2, max_digits=6)),
                ('register_time', models.DateField(auto_now_add=True)),
                ('user_type', models.CharField(max_length=3)),
                ('last_login_time', models.DateTimeField(auto_now=True)),
                ('security_num', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'user_info_table',
            },
        ),
        migrations.AddField(
            model_name='recharge_record_table',
            name='user_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsapp.User_info_table'),
        ),
        migrations.AddField(
            model_name='parking_financial_table',
            name='user_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsapp.User_info_table'),
        ),
        migrations.AddField(
            model_name='garage_parking_state_table',
            name='user_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olsapp.User_info_table'),
        ),
        migrations.AddField(
            model_name='garage_exception_table',
            name='garage_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsapp.Garage_info_table'),
        ),
        migrations.AddField(
            model_name='garage_exception_table',
            name='user_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsapp.User_info_table'),
        ),
    ]
