# Generated by Django 2.1.7 on 2019-06-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage_info_table',
            name='camera_id',
            field=models.CharField(default='000000000000', max_length=12),
        ),
        migrations.AddField(
            model_name='garage_info_table',
            name='side_control',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='garage_parking_state_table',
            name='car_color',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='garage_parking_state_table',
            name='car_id',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='garage_parking_state_table',
            name='car_logo',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='garage_parking_state_table',
            name='car_type',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='garage_parking_state_table',
            name='parking_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
