# Generated by Django 2.1.7 on 2019-06-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsapp', '0002_auto_20190602_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage_parking_state_table',
            name='car_color',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='garage_parking_state_table',
            name='car_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='garage_parking_state_table',
            name='car_logo',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='garage_parking_state_table',
            name='car_type',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
