# Generated by Django 2.1.7 on 2019-06-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsapp', '0003_auto_20190606_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage_info_table',
            name='garage_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='garage_info_table',
            name='camera_id',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='garage_info_table',
            name='side_control',
            field=models.CharField(max_length=1),
        ),
    ]
