# Generated by Django 2.1.7 on 2019-06-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsapp', '0005_auto_20190606_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage_parking_state_table',
            name='charge_power',
            field=models.DecimalField(decimal_places=1, default=1.8, max_digits=3),
        ),
        migrations.AddField(
            model_name='garage_parking_state_table',
            name='charge_voltage',
            field=models.DecimalField(decimal_places=1, default=233.8, max_digits=4),
        ),
    ]
