# Generated by Django 2.1.7 on 2019-06-23 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olsapp', '0006_auto_20190608_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investors_table',
            fields=[
                ('investment_num', models.AutoField(primary_key=True, serialize=False)),
                ('super_user', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('garage', models.ManyToManyField(to='olsapp.Garage_info_table')),
            ],
            options={
                'db_table': 'investors_table',
            },
        ),
        migrations.CreateModel(
            name='Supervisors_table',
            fields=[
                ('supervisor_num', models.AutoField(primary_key=True, serialize=False)),
                ('admin_user', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('admin_type', models.SmallIntegerField()),
                ('investor_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsapp.Investors_table')),
            ],
            options={
                'db_table': 'supervisors_table',
            },
        ),
        migrations.AlterField(
            model_name='garage_parking_state_table',
            name='charge_power',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='garage_parking_state_table',
            name='charge_voltage',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
