# Generated by Django 2.1.7 on 2019-07-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsapp', '0007_auto_20190623_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='investors_table',
            name='investor_name',
            field=models.CharField(default='san;\x08', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investors_table',
            name='garage',
            field=models.ManyToManyField(null=True, to='olsapp.Garage_info_table'),
        ),
    ]
