# Generated by Django 2.1.7 on 2020-01-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsapp', '0008_auto_20190730_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage_parking_state_table',
            name='matrix_side_x',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='garage_parking_state_table',
            name='matrix_side_y',
            field=models.IntegerField(default=-1),
        ),
    ]
