# Generated by Django 2.1.7 on 2020-02-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsapp', '0009_auto_20200131_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage_parking_state_table',
            name='bluetooth_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='garage_parking_state_table',
            name='bluetooth_password',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='garage_parking_state_table',
            name='is_subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
