# Generated by Django 2.1.7 on 2020-02-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olsapp', '0010_auto_20200210_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage_parking_state_table',
            name='cell_sys_state',
            field=models.IntegerField(default=0),
        ),
    ]
