# Generated by Django 2.1.7 on 2019-04-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='0', max_length=30)),
                ('payload', models.CharField(default='0', max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'test_log',
            },
        ),
    ]
