# Generated by Django 2.1.7 on 2020-04-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmqttapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HB_Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_now', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hb_hardware',
            },
        ),
    ]
